name: organize_ai_app
description: "Organize AI."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.0.3
  http: ^1.2.2
  provider: ^6.0.0
  flutter_secure_storage: ^9.0.0
  catppuccin_flutter: ^1.0.0
  path: ^1.8.0
  file_picker: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/